/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.crisma.worldstate.editor;

import org.openide.util.NbBundle;

import javax.swing.JComponent;

import de.cismet.cids.custom.crisma.worldstate.viewer.ICCDataDetailMiniatureView;
import de.cismet.cids.custom.crisma.worldstate.viewer.ICCDataDetailView;

import de.cismet.cids.dynamics.CidsBean;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class ICCDataDetailEditor extends AbstractDetailEditor {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private final transient ICCDataDetailMiniatureView mEditor = new ICCDataDetailMiniatureView();
    private final transient ICCDataDetailView editor = new ICCDataDetailView();

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ICCDataDetailEditor.
     */
    public ICCDataDetailEditor() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ayuthaya", 1, 48));                                               // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(NbBundle.getMessage(ICCDataDetailEditor.class, "ICCDataDetailEditor.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(NbBundle.getMessage(
                ICCDataDetailEditor.class,
                "ICCDataDetailEditor.jLabel1.toolTipText"));                                                 // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }                                                                                                        // </editor-fold>//GEN-END:initComponents

    @Override
    public JComponent getEditor() {
        return editor;
    }

    @Override
    public void setWorldstate(final CidsBean worldstate) {
        super.setWorldstate(worldstate);
        mEditor.setWorldstate(worldstate);
        editor.setWorldstate(worldstate);
    }

    @Override
    public JComponent getMiniatureEditor() {
        return mEditor;
    }

    @Override
    public String getId() {
        return "icc_data_editor";
    }

    @Override
    public String getDisplayName() {
        return "ICC Data (autoupdate on save)";
    }
}
