/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.crisma.worldstate.editor;

import org.openide.util.NbBundle;

import javax.swing.JComponent;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class PopulationAndBuildingsDetailEditor extends AbstractDetailEditor {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form PopulationAndBuildingsDetailEditor.
     */
    public PopulationAndBuildingsDetailEditor() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jTextField1.setText(NbBundle.getMessage(
                PopulationAndBuildingsDetailEditor.class,
                "PopulationAndBuildingsDetailEditor.jTextField1.text")); // NOI18N
        add(jTextField1, java.awt.BorderLayout.CENTER);
    }                                                                    // </editor-fold>//GEN-END:initComponents

    @Override
    public JComponent getEditor() {
        return this;
    }

    @Override
    public JComponent getMiniatureEditor() {
        return this;
    }

    @Override
    public String getId() {
        return getClass().getCanonicalName();
    }

    @Override
    public String getDisplayName() {
        return "Population and buildings";
    }
}
